import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { performance } from 'node:perf_hooks';
import { ROOT,CASES,INPUTS,sha256,canonicalJson,loadLock,safeRelative,checkedPath } from '../src/handoff-v1.mjs';
const COMMIT='473f9cac98f6ed83446e46b692db77c76b9be524';
const PINS={'docs/integration-contract.md':'fa16c825f8ad244beb21b470c56876a20ac267520e67bb2a1766447724ab764a','schemas/agent-run-receipt-v1.schema.json':'0535d3d2b748c1b2ef88a09164cd99570726d1b20dc8ad204e5bf02410148f8e','schemas/cli-result-v1.schema.json':'d7d2cf25f6464bc4862a4e542c5b9736734973c6d23116284d7941b05644f73b'};
const fixture=path.join(ROOT,'fixtures/handoff-v1');
const launch='import runpy,sys; root=sys.argv[1]; sys.path.insert(0,root); sys.argv=[root+"/evidencegate.py"]+sys.argv[2:]; runpy.run_path(sys.argv[0],run_name="__main__")';

test('sealed synthetic recipe and pinned native reproduction (required, never skipped)',()=>{
 const started=performance.now();const materialize=process.env.DAID_FIXTURE_MODE==='materialize';assert.ok(!process.env.DAID_FIXTURE_MODE||materialize,'unsupported fixture mode');assert.match(process.versions.node,/^20\./);
 for(const k of ['DAID_EG_ROOT','DAID_PYTHON_EXECUTABLE','DAID_PROOF','DAID_PUBLIC_TARGET'])assert.ok(process.env[k],`${k} is required`);
 const proof=fs.realpathSync(process.env.DAID_PROOF),eg=fs.realpathSync(process.env.DAID_EG_ROOT),python=process.env.DAID_PYTHON_EXECUTABLE;
 assert.ok(path.isAbsolute(python)&&fs.statSync(python).isFile());checkedPath(eg,{directory:true});checkedPath(proof,{directory:true});assert.equal(fs.realpathSync(process.env.DAID_PUBLIC_TARGET),ROOT);assert.ok(!proof.startsWith(ROOT+'/')&&!proof.startsWith(eg+'/'));assert.notEqual(proof,ROOT);assert.notEqual(proof,eg);
 const env={...process.env,GIT_OPTIONAL_LOCKS:'0',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',LC_ALL:'C'};const costs=[];
 function command(executable,args,options={}){const t=performance.now();const r=spawnSync(executable,args,{env,encoding:'utf8',timeout:30000,maxBuffer:16*1024*1024,...options});costs.push({order:costs.length+1,kind:options.kind??'setup',executable,args,elapsed_ms:performance.now()-t,exit:r.status});assert.ifError(r.error);return r;}
 function git(root,...args){const r=command('git',['-c','core.hooksPath=/dev/null','-C',root,...args]);assert.equal(r.status,0,r.stderr);return r.stdout;}
 function pin(){assert.equal(git(eg,'rev-parse','HEAD').trim(),COMMIT);assert.equal(git(eg,'status','--porcelain=v1','--untracked-files=all','--ignored'),'');for(const name of git(eg,'ls-tree','-r','--name-only','-z',COMMIT).split('\0').filter(Boolean)){assert.ok(safeRelative(name));const p=path.join(eg,name);assert.ok(fs.lstatSync(p).isFile());const r=command('git',['-C',eg,'show',COMMIT+':'+name],{encoding:null});assert.equal(r.status,0);assert.deepEqual(fs.readFileSync(p),r.stdout,name);}for(const [name,h] of Object.entries(PINS))assert.equal(sha256(fs.readFileSync(path.join(eg,name))),h);return git(eg,'rev-parse',COMMIT+':evidencegate.py').trim();}
 const blob=pin();const v=command(python,['-I','-S','-B','-c','import sys; print(sys.version.split()[0])']);assert.equal(v.status,0,v.stderr);const pyVersion=v.stdout.trim();const versionRun=command(python,['-I','-S','-B','-c','import sys,tomllib; print(tomllib.load(open(sys.argv[1],"rb"))["project"]["version"])',path.join(eg,'pyproject.toml')]);assert.equal(versionRun.status,0,versionRun.stderr);const version=versionRun.stdout.trim();
 let lock;if(!materialize){assert.ok(process.env.DAID_LOCK_SHA256,'reviewed external lock digest required');lock=loadLock(path.join(fixture,'execution-lock.json'),process.env.DAID_LOCK_SHA256).lock;assert.equal(lock.runtimes.node,process.versions.node);assert.equal(lock.runtimes.python,pyVersion);assert.equal(lock.evidencegate.version,version);assert.equal(lock.evidencegate.commit,COMMIT);}
 if(materialize)for(const c of CASES)for(const n of ['packet.json','receipt.json','result.json','observations.json','expectations.txt','report.csv'])assert.ok(!fs.existsSync(path.join(fixture,c,n)),'refuse generated input overwrite');
 if(materialize)assert.ok(!fs.existsSync(path.join(fixture,'execution-lock.json')),'refuse lock overwrite');
 const prep=performance.now(),recipe=JSON.parse(fs.readFileSync(path.join(fixture,'repository-recipe.json'))),repo=path.join(proof,'repository'),revisions={};
 if(!fs.existsSync(repo)){fs.mkdirSync(repo);assert.equal(command('git',['init','--object-format=sha1',repo]).status,0);for(const c of recipe.commits){const entries=[];for(const f of c.files){assert.ok(safeRelative(f.path));assert.equal(f.mode,'100644');const blobRun=command('git',['-C',repo,'hash-object','-w','--stdin'],{input:f.text});assert.equal(blobRun.status,0);entries.push(`${f.mode} blob ${blobRun.stdout.trim()}\t${f.path}\n`);}const tree=command('git',['-C',repo,'mktree'],{input:entries.sort().join('')});assert.equal(tree.status,0);const commitEnv={...env,GIT_AUTHOR_NAME:recipe.identity.name,GIT_AUTHOR_EMAIL:recipe.identity.email,GIT_COMMITTER_NAME:recipe.identity.name,GIT_COMMITTER_EMAIL:recipe.identity.email,GIT_AUTHOR_DATE:c.timestamp,GIT_COMMITTER_DATE:c.timestamp};const cr=command('git',['-c','commit.gpgsign=false','-C',repo,'commit-tree',tree.stdout.trim(),...c.parents.flatMap(id=>['-p',revisions[id]])],{env:commitEnv,input:c.message+'\n'});assert.equal(cr.status,0,cr.stderr);revisions[c.id]=cr.stdout.trim();}git(repo,'checkout','--detach',revisions.R1);fs.writeFileSync(path.join(proof,'repository-revisions.json'),canonicalJson(revisions),{flag:'wx'});}else{Object.assign(revisions,JSON.parse(fs.readFileSync(path.join(proof,'repository-revisions.json'))));assert.equal(git(repo,'rev-parse','HEAD').trim(),revisions.R1);}
 assert.equal(git(repo,'status','--porcelain=v1','--untracked-files=all','--ignored'),'');if(lock)assert.equal(canonicalJson(revisions),canonicalJson(lock.repository_revisions));
 costs.push({order:costs.length+1,kind:'synthetic-repository-preparation',elapsed_ms:performance.now()-prep});
 const artifact=fs.readFileSync(path.join(repo,'report.csv')),artifactHash=sha256(artifact),prepared=[];
 function state(){return {revision:git(repo,'rev-parse','HEAD').trim(),dirty:!!git(repo,'status','--porcelain=v1','--untracked-files=all')};}
 for(const c of CASES){const oracle=JSON.parse(fs.readFileSync(path.join(fixture,c,'expected.json')));assert.equal(oracle.case,c);assert.ok([0,1,2].includes(oracle.required_native_verify_exit));const caseStart=performance.now(),dir=path.join(proof,c);fs.mkdirSync(dir,{recursive:true});const revision=c==='wrong-revision'?revisions.R0:revisions.R1,ids=Array.from({length:c==='missing-check'?18:20},(_,i)=>'c'+String(i+1).padStart(2,'0'));const subject={id:recipe.subject_id,revision:revisions.R1,attempt_id:recipe.attempt_id};
 const receipt={schema_version:1,summary:'Synthetic receipt; records are not proof that checks ran.',subject:{type:'git_change',base_sha:revisions.B0,head_sha:revision},scope:{allowed_paths:['report.csv'],protected_prefixes:[]},files_touched:['report.csv'],checks:ids.map(id=>({id,name:'Synthetic '+id,command:'synthetic-record-only '+id,status:'passed',summary:'Synthetic supplied observation; command not executed.',scope:'report.csv',revision,required:true})),claims:[{id:'synthetic-checks',text:'Only the checks listed in this synthetic receipt are declared.',evidence_refs:ids}],risks:['Synthetic provenance; no authenticity or execution certification.'],human_review:{status:'approved',reviewer:'Synthetic reviewer',reviewed_head_sha:revision,summary:'Synthetic record only; no publication authority.'},public_safety:{status:'reviewed',reviewed_head_sha:revision,summary:'Disposable synthetic fixture only.'}};
 const receiptBytes=c==='invalid-source'?Buffer.from('{"schema_version":'):Buffer.from(canonicalJson(receipt));const receiptPath=path.join(dir,'receipt.json');if(fs.existsSync(receiptPath))assert.deepEqual(fs.readFileSync(receiptPath),receiptBytes);else fs.writeFileSync(receiptPath,receiptBytes,{flag:'wx'});
 const captures={};for(const operation of ['validate','verify']){pin();const before=state();const args=['-I','-S','-B','-c',launch,eg,operation,receiptPath,...(operation==='verify'?['--repo',repo]:[]),'--format','json'];const captured_at=new Date().toISOString();const result=command(python,args,{kind:'native-'+operation});const after=state();pin();const expectedExit=operation==='verify'?oracle.required_native_verify_exit:c==='invalid-source'?2:0;
 const invocation={observer_id:'native-capture',origin:'locally-observed',captured_at,tool_version:version,tool_commit:COMMIT,operation,exit_status:result.status,receipt_sha256:sha256(receiptBytes),result_sha256:sha256(result.stdout),repository_before:operation==='verify'?before:null,repository_after:operation==='verify'?after:null};const capture={command:[python,...args],exit:result.status,invocation,evidencegate_py_blob:blob,evidencegate_py_sha256:sha256(fs.readFileSync(path.join(eg,'evidencegate.py'))),pyproject_sha256:sha256(fs.readFileSync(path.join(eg,'pyproject.toml'))),node_version:process.versions.node,python_version:pyVersion};const outDir=fs.mkdtempSync(path.join(dir,operation+'-'));fs.writeFileSync(path.join(outDir,'stdout'),result.stdout);fs.writeFileSync(path.join(outDir,'stderr'),result.stderr);fs.writeFileSync(path.join(outDir,'invocation.json'),canonicalJson(capture));
 assert.equal(result.status,expectedExit,`COMPATIBILITY HOLD ${c} ${operation}: ${result.stdout} ${result.stderr}`);const native=JSON.parse(result.stdout);if(c==='wrong-revision'&&operation==='verify')assert.ok(native.findings.some(f=>f.code==='repository_revision_mismatch'));assert.deepEqual(before,after);assert.equal(before.dirty,false);captures[operation]={...capture,stdout:result.stdout,stderr:result.stderr};}
 const observations={schema_version:'daid_handoff_observations_v1',observer:{id:recipe.observer_id,version:'1.0.0',origin:'synthetic'},subject,captured_at:recipe.captured_at,capture:Object.fromEntries(['shared','repository','checks','artifact'].map(k=>[k,{completeness:'complete',warnings:[]}])),repository:{before:state(),after:state()},checks:ids.map(id=>({id,attempt_id:recipe.attempt_id,revision,outcome:'executed-passed'})),artifact:{path:'report.csv',state:'present',sha256:artifactHash,before_sha256:artifactHash,stable:true},writes:c==='unbound-artifact'?[]:[{id:'synthetic-write-1',path:'report.csv',attempt_id:recipe.attempt_id,revision,outcome:'created',sha256:artifactHash}],verifier_invocation:captures.verify.invocation};
 let expectation='',requirements=[];for(let i=1;i<=20;i++){const check_id='c'+String(i).padStart(2,'0'),text=`Run declared check ${check_id}.`,start=Buffer.byteLength(expectation);expectation+=text+'\n';requirements.push({id:'required-'+check_id,kind:'check',text,span:{start,end:start+Buffer.byteLength(text)},check_id,artifact_path:null});}const text='Create report.csv in the claimed attempt.',start=Buffer.byteLength(expectation);expectation+=text+'\n';requirements.push({id:'required-report',kind:'artifact',text,span:{start,end:start+Buffer.byteLength(text)},check_id:null,artifact_path:'report.csv'});
 const assertions=[],statements=[['A','The receipt records this revision.','receipt_revision',[]],['B','All twenty declared checks ran in this attempt.','all_checks_ran',requirements.filter(r=>r.kind==='check').map(r=>r.id)],['C','This attempt created report.csv.','artifact_created',['required-report']]];let statement='';for(const [id,text,predicate,requirement_ids] of statements){const start=Buffer.byteLength(statement);statement+=text+'\n';assertions.push({id,text,predicate,requirement_ids,span:{start,end:start+Buffer.byteLength(text)}});}
 const files={'receipt.json':receiptBytes,'result.json':Buffer.from(captures.verify.stdout),'observations.json':Buffer.from(canonicalJson(observations)),'expectations.txt':Buffer.from(expectation),'report.csv':artifact};const packet={schema_version:'daid_handoff_packet_v1',statement,operator:{id:'synthetic-operator',confirmed:true},subject,sources:['expectations','receipt','result','observations','artifact'].map(role=>{const name={expectations:'expectations.txt',artifact:'report.csv'}[role]??role+'.json';return {id:role,role,path:name,sha256:sha256(files[name]),origin:{kind:'synthetic',attributed_to:'Synthetic fixture preparation'}};}),expectations_complete:true,requirements,assertions,narrower_observation:{id:'N',text:'report.csv is present with the selected digest at this snapshot.',artifact_path:'report.csv',sha256:artifactHash},capture_gaps:[],contract_id:'daid_handoff_mapping_v1'};files['packet.json']=Buffer.from(canonicalJson(packet));
 if(materialize)prepared.push({c,files});else {for(const n of ['receipt.json','expectations.txt','report.csv'])assert.deepEqual(files[n],fs.readFileSync(path.join(fixture,c,n)),c+'/'+n);assert.deepEqual(Buffer.from(captures.verify.stdout),fs.readFileSync(path.join(fixture,c,'result.json')),c+' complete native verify output');const sealed=JSON.parse(fs.readFileSync(path.join(fixture,c,'observations.json')));assert.equal(sealed.verifier_invocation.operation,'verify');assert.equal(sealed.verifier_invocation.tool_commit,COMMIT);assert.equal(sealed.verifier_invocation.tool_version,version);}
 costs.push({order:costs.length+1,kind:'case-preparation-and-native-capture',case:c,elapsed_ms:performance.now()-caseStart});
 }
 if(materialize){for(const {c,files} of prepared)for(const [n,bytes] of Object.entries(files))fs.writeFileSync(path.join(fixture,c,n),bytes,{flag:'wx'});const newLock={schema_version:'daid_handoff_execution_lock_v1',semantic_sha256:'612f39689c90a2f6b4b47df30ecaf7e3c21a0058241c0e898d293f9f4c908bd1',public_baseline:'69a7eefe10de26893ca5f58b6625c54edc36758a',evidencegate:{commit:COMMIT,version,source_sha256:PINS},runtimes:{node:process.versions.node,python:pyVersion},repository_revisions:revisions,inputs:INPUTS.map(p=>({path:p,sha256:sha256(fs.readFileSync(path.join(ROOT,p)))}))};fs.writeFileSync(path.join(fixture,'execution-lock.json'),canonicalJson(newLock),{flag:'wx'});console.log('Candidate materialized; STOP for independent external lock sealing. No acceptance replay performed.');}
 pin();assert.equal(git(repo,'status','--porcelain=v1','--untracked-files=all','--ignored'),'');const receipt={mode:materialize?'materialize':'replay',elapsed_ms:performance.now()-started,command_count:costs.filter(c=>c.executable).length,native_validate_count:5,native_verify_count:5,costs,earlier_setup_and_assistance_costs:'unavailable',tokens:'unavailable',monetary_cost:'unavailable'};fs.writeFileSync(path.join(proof,`reproduction-cost-${materialize?'materialize':'replay'}-${Date.now()}.json`),canonicalJson(receipt),{flag:'wx'});
});
