import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { ROOT,CASES,INPUTS,strictJson,sha256,canonicalJson,shape,evaluatePacketBytes,loadLock,checkPacket,collectSelectionBytes,markdown } from '../src/handoff-v1.mjs';
import { evaluateAgentClaimBytes } from '../src/agent-claim-check.mjs';
const fixture=path.join(ROOT,'fixtures/handoff-v1');
const digest=process.env.DAID_LOCK_SHA256;
// This suite is acceptance replay: external review must supply the digest.
const lock=loadLock(path.join(fixture,'execution-lock.json'),digest).lock;
function copyCase(name='control'){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'daid-handoff-test-')));for(const n of ['packet.json','expectations.txt','receipt.json','result.json','observations.json','report.csv','expected.json'])fs.copyFileSync(path.join(fixture,name,n),path.join(dir,n));return dir;}
function object(dir,n){return JSON.parse(fs.readFileSync(path.join(dir,n+'.json')));}
function write(dir,n,v){fs.writeFileSync(path.join(dir,n+'.json'),canonicalJson(v));}
function refresh(dir,{bind=true}={}){const p=object(dir,'packet'),m=object(dir,'observations');if(bind&&m.verifier_invocation){m.verifier_invocation.receipt_sha256=sha256(fs.readFileSync(path.join(dir,'receipt.json')));m.verifier_invocation.result_sha256=sha256(fs.readFileSync(path.join(dir,'result.json')));write(dir,'observations',m);}for(const s of p.sources)if(s.sha256!==null)s.sha256=sha256(fs.readFileSync(path.join(dir,s.path)));write(dir,'packet',p);}
const report=dir=>evaluatePacketBytes(fs.readFileSync(path.join(dir,'packet.json')),dir,lock,digest);
function findings(r){return r.assessments.map(a=>a.status==='assessed'?a.acc_receipt.finding:'error-no-finding');}
function mutation(change,{bind=true}={}){const dir=copyCase();try{change(dir);refresh(dir,{bind});return report(dir);}finally{fs.rmSync(dir,{recursive:true});}}
const S='supported',I='insufficient_evidence',C='contradicted',E='error-no-finding';

function assertOracle(report,expected){
 assert.deepEqual(findings(report),expected.findings,expected.case);
 assert.deepEqual(report.coverage.missing_check_ids,expected.missing_check_ids,expected.case);
 for(const limitation of expected.limitations)assert.ok(report.native_context.limitations.includes(limitation),`${expected.case}: missing required limitation ${limitation}`);
 assert.equal(report.native_context.invocation?.operation,'verify',expected.case);
 assert.equal(report.native_context.invocation?.exit_status,expected.required_native_verify_exit,expected.case);
}
test('five frozen oracles, complete denominators, source provenance, and unchanged ACC outputs',()=>{for(const c of CASES){const r=report(path.join(fixture,c)),expected=object(path.join(fixture,c),'expected');assert.deepEqual(shape('report',r),[],c);assertOracle(r,expected);assert.equal(r.downstream_action_authorized,false);assert.equal(r.intent_assessment,'not-assessed');assert.ok(r.sources.every(s=>s.descriptor.origin.kind==='synthetic'));for(const a of r.assessments){if(a.status==='assessed')assert.deepEqual(a.acc_receipt,evaluateAgentClaimBytes(Buffer.from(canonicalJson(a.acc_input))).value);else assert.equal(a.acc_receipt,null);}if(c==='missing-check'){assert.equal(r.coverage.expected_check_ids.length,20);assert.equal(r.coverage.observed_check_ids.length,18);assert.equal(r.native_context.result.ok,true);assert.equal(r.native_context.result.operation,'verify');assert.equal(r.native_context.receipt.checks.length,18);}if(c==='wrong-revision')assert.ok(r.native_context.result.findings.some(f=>f.code==='repository_revision_mismatch'));if(c==='invalid-source')assert.equal(r.native_context.linkage,'invalid');}});
test('canonical renderings preserve full report deterministically with no active embeds',()=>{const dir=copyCase();try{const p=object(dir,'packet');p.statement+='<script>alert(1)</script> ![x](https://invalid.example)';write(dir,'packet',p);const r=report(dir);assert.equal(canonicalJson(r),canonicalJson(report(dir)));assert.equal(markdown(r),markdown(report(dir)));assert.ok(markdown(r).includes('&lt;script&gt;'));assert.ok(!markdown(r).includes('<script>'));assert.equal(canonicalJson(JSON.parse(canonicalJson(r))),canonicalJson(r));}finally{fs.rmSync(dir,{recursive:true});}});
test('check outcome means ran, with skipped conflicts and failed execution retained',()=>{for(const [outcome,expected] of [['skipped',C],['executed-failed',S],['not-observed',I]]){const r=mutation(d=>{const m=object(d,'observations');m.checks[19].outcome=outcome;write(d,'observations',m);});assert.deepEqual(findings(r),[S,expected,S,S]);assert.ok(r.assessments[1].acc_input.evidence.some(e=>e.observed_value===outcome));}});
test('invocation omission and binding errors never suppress independent assessments',()=>{const absent=mutation(d=>{const m=object(d,'observations');m.verifier_invocation=null;write(d,'observations',m);});assert.deepEqual(findings(absent),[S,S,S,S]);assert.equal(absent.native_context.linkage,'unbound');assert.equal(absent.incomplete,true);for(const mutate of [i=>i.receipt_sha256='0'.repeat(64),i=>i.operation='validate',i=>i.exit_status=1,i=>i.tool_version='wrong']){const r=mutation(d=>{const m=object(d,'observations');mutate(m.verifier_invocation);write(d,'observations',m);},{bind:false});assert.deepEqual(findings(r),[S,S,S,S]);assert.ok(r.native_context.errors.some(e=>e.code==='binding_mismatch'));assert.equal(r.native_context.linkage,'invalid');}});
test('result operation and repository_checked consistency is native context only',()=>{const r=mutation(d=>{const n=object(d,'result');n.repository_checked=false;write(d,'result',n);});assert.deepEqual(findings(r),[S,S,S,S]);assert.ok(r.native_context.errors.some(e=>e.source_id==='result'&&e.code==='binding_mismatch'));assert.equal(r.native_context.repository_binding,'not-checked');});
test('manifest version and null artifact admission isolate only dependent assessments',()=>{const r=mutation(d=>{const m=object(d,'observations');m.schema_version='future';write(d,'observations',m);const p=object(d,'packet');p.sources.find(s=>s.role==='artifact').sha256=null;write(d,'packet',p);});assert.deepEqual(findings(r),[S,E,E,E]);assert.equal(r.sources.find(s=>s.descriptor.role==='artifact').admission,'not-read');assert.ok(r.errors.every(e=>e.source_id==='observations'));assert.equal(r.coverage.observed_check_ids,null);});
test('invalid receipt JSON and digest preserve the other three assessments',()=>{const r=mutation(d=>fs.writeFileSync(path.join(d,'receipt.json'),'{'));assert.deepEqual(findings(r),[E,S,S,S]);assert.ok(r.sources.find(s=>s.descriptor.role==='receipt').observed_sha256);const dir=copyCase();try{const p=object(dir,'packet');p.sources.find(s=>s.role==='receipt').sha256='0'.repeat(64);write(dir,'packet',p);assert.deepEqual(findings(report(dir)),[E,S,S,S]);}finally{fs.rmSync(dir,{recursive:true});}});
test('subject attempt mismatch is inapplicable and leaves snapshot distinct',()=>{const r=mutation(d=>{const m=object(d,'observations');m.subject.attempt_id='other';write(d,'observations',m);});assert.deepEqual(findings(r),[S,I,I,S]);assert.ok(r.assessments[2].acc_input.evidence.some(e=>e.state==='inapplicable'));});
test('expectations false and unknown scope capture to B and C',()=>{for(const value of [false,null]){const r=mutation(d=>{const p=object(d,'packet');p.expectations_complete=value;write(d,'packet',p);});assert.deepEqual(findings(r),[S,I,I,S]);assert.equal(r.assessments[1].acc_input.capture.completeness,value===null?'unknown':'partial');}});
test('unknown assertion remains unassessed and unmapped requirements are visible',()=>{const r=mutation(d=>{const p=object(d,'packet');const start=Buffer.byteLength(p.statement);p.statement+='Done';p.assertions.push({id:'D',text:'Done',span:{start,end:start+4},predicate:'unassessed',requirement_ids:[]});p.assertions[2].predicate='unassessed';write(d,'packet',p);});assert.equal(r.assessments.find(a=>a.id==='D').status,'unassessed');assert.equal(r.incomplete,true);assert.deepEqual(r.coverage.unmapped_requirement_ids,['required-report']);});
test('repository dirty/unavailable/changed never downgrades independent stable snapshot',()=>{for(const change of [m=>m.repository.before.dirty=true,m=>m.repository.before=null,m=>m.repository.after.revision=lock.repository_revisions.R0]){const r=mutation(d=>{const m=object(d,'observations');change(m);write(d,'observations',m);});assert.deepEqual(findings(r),[S,I,I,S]);}});
test('artifact instability/unavailability is local to C/N; stable absence is not creation refutation',()=>{for(const state of ['unstable','unavailable','absent']){const r=mutation(d=>{const m=object(d,'observations');if(state==='unstable')m.artifact.stable=false;else{m.artifact.state=state;m.artifact.sha256=null;m.artifact.stable=state==='absent'?true:null;const p=object(d,'packet');p.sources.find(s=>s.role==='artifact').sha256=null;write(d,'packet',p);}write(d,'observations',m);});assert.deepEqual(findings(r),[S,S,I,state==='absent'?C:I]);}});
test('artifact integrity errors and inconsistent null digest suppress C/N only',()=>{for(const kind of ['digest','null']){const dir=copyCase();try{const p=object(dir,'packet');p.sources.find(s=>s.role==='artifact').sha256=kind==='null'?null:'0'.repeat(64);write(dir,'packet',p);assert.deepEqual(findings(report(dir)),[S,S,E,E]);}finally{fs.rmSync(dir,{recursive:true});}}});
test('created/not-created mixed events retain contradictions and other-attempt limitations',()=>{const r=mutation(d=>{const m=object(d,'observations');m.writes.push({...m.writes[0],id:'negative',outcome:'not-created',sha256:null});m.writes.push({...m.writes[0],id:'other',attempt_id:'other-attempt'});write(d,'observations',m);});assert.deepEqual(findings(r),[S,S,C,S]);const ev=r.assessments[2].acc_input.evidence;assert.ok(ev.some(e=>e.state==='contradictory'));assert.ok(ev.some(e=>e.state==='inapplicable'));assert.ok(ev.some(e=>e.id==='event-synthetic-write-1'&&e.state==='supports'));});
test('component warnings preserve ordered duplicates and packet gaps append last',()=>{const r=mutation(d=>{const m=object(d,'observations');m.capture.shared.warnings=['shared'];m.capture.repository.warnings=['repo','repo'];m.capture.checks.warnings=['checks'];m.repository.before.dirty=true;write(d,'observations',m);const p=object(d,'packet');p.expectations_complete=false;p.capture_gaps=['packet'];write(d,'packet',p);});assert.deepEqual(r.assessments[1].acc_input.capture.adapter_warnings,['shared','repo','repo','repository dirty','checks','expectation list incomplete','packet']);assert.deepEqual(r.assessments[3].acc_input.capture.adapter_warnings,['shared','packet']);assert.deepEqual(r.assessments[0].acc_input.capture.adapter_warnings,['packet']);});
test('expectation span errors suppress B/C; statement/reference/narrower ID errors reject packet',()=>{const r=mutation(d=>{const p=object(d,'packet');p.requirements[0].span.end=999999;write(d,'packet',p);});assert.deepEqual(findings(r),[S,E,E,S]);assert.equal(r.coverage.expected_check_ids,null);for(const change of [p=>p.assertions[0].span.end=999999,p=>p.assertions[0].requirement_ids=['missing'],p=>p.narrower_observation.id='A']){const bad=mutation(d=>{const p=object(d,'packet');change(p);write(d,'packet',p);});assert.equal(bad.schema_version,'daid_handoff_error_v1');assert.equal(bad.errors[0].code,'invalid_mapping');}});
test('strict JSON rejects duplicates, bad UTF-8, nonfinite, trailing data and limits',()=>{for(const input of ['{"a":1,"a":2}','{} false','{"a":NaN}','1e999','"\\ud800"','{"a":1,}'])assert.throws(()=>strictJson(Buffer.from(input)));assert.throws(()=>strictJson(Buffer.from([0xff])));assert.throws(()=>strictJson(Buffer.alloc(8*1024*1024+1,32)));assert.throws(()=>strictJson(Buffer.from('['.repeat(130)+'0'+']'.repeat(130))));assert.equal(strictJson(Buffer.from('{"ok":true}')).ok,true);});
test('lock missing/mismatch/unknown field/input mismatch fail before sources',()=>{for(const expected of [undefined,'bad','0'.repeat(64)]){const r=checkPacket('/nonexistent',path.join(fixture,'execution-lock.json'),expected);assert.equal(r.errors[0].code,'execution_lock_missing');assert.equal(r.packet_sha256,null);}const d=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'daid-lock-test-')));try{for(const change of [l=>l.extra=true,l=>l.inputs[0].sha256='0'.repeat(64),l=>l.inputs.reverse(),l=>l.inputs[0].path=l.inputs[1].path]){const l=structuredClone(lock);change(l);const bytes=Buffer.from(canonicalJson(l)),p=path.join(d,'lock.json');fs.writeFileSync(p,bytes);assert.throws(()=>loadLock(p,sha256(bytes)));}}finally{fs.rmSync(d,{recursive:true});}});
test('collector metadata only, source preservation, absent artifact and unsafe selections',()=>{assert.ok(process.env.DAID_PROOF);const proof=fs.realpathSync(process.env.DAID_PROOF),repo=path.join(proof,'repository');assert.ok(fs.existsSync(repo));const d=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'daid-collector-test-')));const reportPath=path.join(repo,'report.csv'),before=fs.readFileSync(reportPath),status=spawnSync('git',['-C',repo,'status','--porcelain=v1','--untracked-files=all'],{encoding:'utf8'}).stdout;try{const s={schema_version:'daid_handoff_selection_v1',repository_root:repo,evidence_root:d,artifact_path:'report.csv',output_path:path.join(d,'out.json'),subject:{id:'synthetic-handoff',revision:lock.repository_revisions.R1,attempt_id:'synthetic-attempt-1'},observer_id:'collector-test'};const m=collectSelectionBytes(Buffer.from(canonicalJson(s)));assert.deepEqual(shape('observations',m),[]);assert.deepEqual(m.checks,[]);assert.deepEqual(m.writes,[]);assert.equal(m.verifier_invocation,null);assert.equal(m.artifact.stable,true);assert.equal(m.observer.origin,'locally-observed');assert.throws(()=>collectSelectionBytes(Buffer.from(canonicalJson(s))));for(const change of [s=>s.artifact_path='../report.csv',s=>s.output_path=path.join(repo,'new.json')]){const x={...s,output_path:path.join(d,'rejected.json')};change(x);assert.throws(()=>collectSelectionBytes(Buffer.from(canonicalJson(x))));}fs.symlinkSync(repo,path.join(d,'alias'));assert.throws(()=>collectSelectionBytes(Buffer.from(canonicalJson({...s,repository_root:path.join(d,'alias'),output_path:path.join(d,'symlink.json')}))));const absent=collectSelectionBytes(Buffer.from(canonicalJson({...s,artifact_path:'missing.csv',output_path:path.join(d,'absent.json')})));assert.equal(absent.artifact.state,'absent');assert.equal(absent.capture.artifact.completeness,'complete');assert.deepEqual(fs.readFileSync(reportPath),before);assert.equal(spawnSync('git',['-C',repo,'status','--porcelain=v1','--untracked-files=all'],{encoding:'utf8'}).stdout,status);}finally{fs.rmSync(d,{recursive:true});}});
test('CLI has no default reviewed digest and obeys invalid-source exit 2',()=>{for(const c of CASES){const r=spawnSync(process.execPath,['tools/check-handoff.mjs',`fixtures/handoff-v1/${c}/packet.json`,'--execution-lock','fixtures/handoff-v1/execution-lock.json','--execution-lock-sha256',digest,'--format','json'],{cwd:ROOT,encoding:'utf8'});assert.equal(r.status,c==='invalid-source'?2:0,r.stderr);assert.equal(JSON.parse(r.stdout).execution_lock_id,digest);}assert.equal(INPUTS.length,43);const r=spawnSync(process.execPath,['tools/check-handoff.mjs','fixtures/handoff-v1/control/packet.json'],{cwd:ROOT,encoding:'utf8'});assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).errors[0].code,'execution_lock_missing');});

test('UTC timestamp admission rejects impossible calendar dates without normalization',()=>{
 const invocation={observer_id:'observer',origin:'synthetic',captured_at:'2020-02-29T00:00:00Z',tool_version:'0.1.0',tool_commit:'1'.repeat(40),operation:'validate',exit_status:0,receipt_sha256:'1'.repeat(64),result_sha256:'2'.repeat(64),repository_before:null,repository_after:null};
 for(const captured_at of ['2020-02-29T00:00:00Z','2000-02-29T23:59:59.123456Z','2021-01-31T00:00:00Z','2020-04-30T00:00:00Z'])assert.deepEqual(shape('invocation',{...invocation,captured_at}),[],captured_at);
 for(const captured_at of ['2020-02-31T00:00:00Z','2021-02-29T00:00:00Z','1900-02-29T00:00:00Z','2020-00-01T00:00:00Z','2020-13-01T00:00:00Z','2020-01-00T00:00:00Z','2020-04-31T00:00:00Z','2020-01-32T00:00:00Z','2020-01-01T24:00:00Z','2020-01-01T00:60:00Z','2020-01-01T00:00:61Z','2020-01-01T00:00:00+00:00'])assert.ok(shape('invocation',{...invocation,captured_at}).some(e=>e.code==='invalid_shape'&&e.path==='/captured_at'),captured_at);
});
