import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { evaluateAgentClaimBytes, canonicalJson } from './agent-claim-check.mjs';

export { canonicalJson };
export const VERSION = '1.0.0';
export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const CASES = ['control','wrong-revision','missing-check','unbound-artifact','invalid-source'];
export const ALLOWED = ['src/handoff-v1.mjs','tools/check-handoff.mjs','tools/collect-handoff.mjs','schemas/handoff-v1.schema.json','tests/handoff-v1.test.mjs','tests/handoff-reproduction.test.mjs','docs/handoff-v1.md','fixtures/handoff-v1/execution-lock.json','fixtures/handoff-v1/repository-recipe.json',...CASES.flatMap(c=>['packet.json','expectations.txt','receipt.json','result.json','observations.json','report.csv','expected.json'].map(n=>`fixtures/handoff-v1/${c}/${n}`))].sort();
export const INPUTS = ALLOWED.filter(p=>p!=='fixtures/handoff-v1/execution-lock.json');
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const JSON_LIMIT = 8*1024*1024, FILE_LIMIT = 64*1024*1024;
const pointer = s => s.replaceAll('~','~0').replaceAll('/','~1');
const same = (a,b) => typeof a==='string' && typeof b==='string' && a.toLowerCase()===b.toLowerCase();
const issue = (code,source_id,p,message) => ({code,source_id,path:p,message});
class AdmissionError extends Error { constructor(code,p,message){super(message);this.code=code;this.path=p;} }
const fail=(code,p,message)=>{throw new AdmissionError(code,p,message);};
export function strictJson(bytes){
 if(bytes.length>JSON_LIMIT) fail('input_limit','','JSON exceeds 8 MiB');
 let s;try{s=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);}catch{fail('malformed_json','','invalid UTF-8');}
 let i=0;
 const ws=()=>{while(i<s.length&&' \r\n\t'.includes(s[i]))i++;};
 function str(p){const start=i++;while(i<s.length){if(s[i]==='"'){i++;let v;try{v=JSON.parse(s.slice(start,i));}catch{fail('malformed_json',p,'invalid string');}if(!v.isWellFormed())fail('malformed_json',p,'unpaired surrogate');return v;}if(s[i]==='\\')i++;i++;}fail('malformed_json',p,'unterminated string');}
 function value(p,d){if(d>128)fail('input_limit',p,'JSON nesting exceeds 128');ws();const c=s[i];if(c==='"')return str(p);if(c==='{'||c==='['){i++;const isObj=c==='{',v=isObj?Object.create(null):[],keys=new Set(),end=isObj?'}':']';ws();if(s[i]===end){i++;return v;}for(;;){ws();let k;if(isObj){if(s[i]!=='"')fail('malformed_json',p,'expected key');k=str(p);if(keys.has(k))fail('duplicate_key',p+'/'+pointer(k),'duplicate key');keys.add(k);ws();if(s[i++]!==':')fail('malformed_json',p,'expected colon');}else k=v.length;v[k]=value(p+'/'+pointer(String(k)),d+1);ws();if(s[i]===end){i++;return v;}if(s[i++]!==',')fail('malformed_json',p,'expected comma');}}for(const [t,v] of [['true',true],['false',false],['null',null]])if(s.startsWith(t,i)){i+=t.length;return v;}const m=s.slice(i).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/);if(m){i+=m[0].length;const v=Number(m[0]);if(!Number.isFinite(v))fail('malformed_json',p,'nonfinite number');return v;}fail('malformed_json',p,'expected value');}
 const v=value('',0);ws();if(i!==s.length)fail('trailing_content','','trailing content');return v;
}
export function safeRelative(p){return typeof p==='string'&&p.length>0&&!path.isAbsolute(p)&&!/[\\\x00-\x1f\x7f]/.test(p)&&!p.split('/').some(x=>!x||x==='.'||x==='..');}
export function checkedPath(p,{directory=false,missing=false}={}){
 if(!path.isAbsolute(p))fail('selection_rejected','','absolute path required');
 const parsed=path.parse(p);let current=parsed.root;const parts=p.slice(parsed.root.length).split(path.sep);
 if(parts.some(x=>!x||x==='.'||x==='..'))fail('selection_rejected','','unsafe absolute path');
 for(let i=0;i<parts.length;i++){current=path.join(current,parts[i]);let st;try{st=fs.lstatSync(current);}catch(e){if(e.code==='ENOENT'&&i===parts.length-1&&missing)return current;throw e;}if(st.isSymbolicLink())fail('selection_rejected','','symlink rejected');if(i<parts.length-1||directory){if(!st.isDirectory())fail('selection_rejected','','directory required');}else if(!st.isFile())fail('selection_rejected','','regular file required');}
 return current;
}
function selected(root,rel){if(!safeRelative(rel))fail('selection_rejected','','unsafe relative path');checkedPath(root,{directory:true});return checkedPath(root+'/'+rel);}
export function readBytes(p,limit=FILE_LIMIT){checkedPath(p);const fd=fs.openSync(p,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const a=fs.fstatSync(fd);if(!a.isFile())fail('selection_rejected','','regular file required');if(a.size>limit)fail('input_limit','','selected file exceeds byte limit');const b=fs.readFileSync(fd);if(b.length>limit)fail('input_limit','','selected file exceeds byte limit');const z=fs.fstatSync(fd),now=fs.lstatSync(p);if(a.dev!==now.dev||a.ino!==now.ino||a.size!==z.size||a.mtimeMs!==z.mtimeMs||a.ctimeMs!==z.ctimeMs)fail('source_unavailable','','selected file changed during reading');return b;}finally{fs.closeSync(fd);}}
const bundle=JSON.parse(fs.readFileSync(new URL('../schemas/handoff-v1.schema.json',import.meta.url),'utf8'));
function validUtcTimestamp(value){
 const parts=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?Z$/.exec(value);
 if(!parts)return false;
 const [year,month,day,hour,minute,second]=parts.slice(1).map(Number);
 const leap=year%4===0&&(year%100!==0||year%400===0);
 const days=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31];
 return month>=1&&month<=12&&day>=1&&day<=days[month-1]&&hour<=23&&minute<=59&&second<=59;
}
export function shape(name,v){
 const errors=[];
 function visit(s,x,p){if(s.$ref)return visit(bundle.$defs[s.$ref.split('/').at(-1)],x,p);if(s.anyOf){if(x===null&&s.anyOf.some(a=>a.type==='null'))return;return visit(s.anyOf.find(a=>a.type!=='null'),x,p);}const bad=m=>errors.push(issue('invalid_shape',null,p,m));if(Object.hasOwn(s,'const')&&x!==s.const){errors.push(issue(p.endsWith('/schema_version')||p.endsWith('/contract_version')?'unsupported_version':'invalid_shape',null,p,'unexpected constant'));return;}if(s.enum&&!s.enum.some(a=>a===x)){bad('unexpected enumeration');return;}if(s.type){const t=x===null?'null':Array.isArray(x)?'array':typeof x;if(s.type==='integer'?!Number.isSafeInteger(x):t!==s.type){bad('invalid type');return;}}
 if(typeof x==='string'){if(s.pattern&&!new RegExp(s.pattern,'u').test(x))bad('invalid string');if(s.nfc&&x!==x.normalize('NFC'))bad('NFC text required');if(s.safePath&&!safeRelative(x))bad('unsafe relative path');if(s.absolutePath&&(!path.isAbsolute(x)||x.split(path.sep).slice(1).some(q=>!q||q==='.'||q==='..')))bad('absolute path required');if(s.utcTime&&!validUtcTimestamp(x))bad('valid UTC timestamp required');}
 if(typeof x==='number'&&s.minimum!==undefined&&x<s.minimum)bad('below minimum');
 if(Array.isArray(x)){if((s.minItems!==undefined&&x.length<s.minItems)||(s.maxItems!==undefined&&x.length>s.maxItems)){errors.push(issue(s.maxItems!==undefined&&x.length>s.maxItems?'input_limit':'invalid_shape',null,p,'array size rejected'));return;}if(s.uniqueItems&&new Set(x.map(a=>canonicalJson(a))).size!==x.length)bad('duplicate array values');if(s.items)x.forEach((a,i)=>visit(s.items,a,p+'/'+i));}
 if(x&&typeof x==='object'&&!Array.isArray(x)&&s.properties){for(const k of s.required??[])if(!Object.hasOwn(x,k))errors.push(issue('invalid_shape',null,p+'/'+pointer(k),'required field missing'));for(const k of Object.keys(x))if(!Object.hasOwn(s.properties,k)&&s.additionalProperties===false)errors.push(issue('invalid_shape',null,p+'/'+pointer(k),'unknown field'));for(const [k,a] of Object.entries(s.properties))if(Object.hasOwn(x,k))visit(a,x[k],p+'/'+pointer(k));}
 }
 visit(bundle.$defs[name],v,'');return errors;
}
const unique=(rows,p)=>{if(new Set(rows.map(x=>x.id)).size!==rows.length)fail('invalid_shape',p,'duplicate IDs');};
function spanMatches(bytes,s,text){if(s.start>=s.end||s.end>bytes.length)return false;try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes.subarray(s.start,s.end))===text;}catch{return false;}}
function admit(name,v){const errors=shape(name,v);if(errors.length){const a=errors[0];fail(a.code,a.path,a.message);}if(name==='packet'){
 unique(v.sources,'/sources');unique(v.requirements,'/requirements');unique(v.assertions,'/assertions');const roles=v.sources.map(s=>s.role);if(roles.length!==5||new Set(roles).size!==5)fail('invalid_shape','/sources','exactly one source of each role required');for(const s of v.sources){if(s.sha256===null&&s.role!=='artifact')fail('invalid_shape','/sources','non-artifact digest required');if((s.origin.kind==='unknown')!==(s.origin.attributed_to===null))fail('invalid_shape','/sources','origin attribution inconsistent');}
 const checks=v.requirements.filter(r=>r.kind==='check'),art=v.requirements.filter(r=>r.kind==='artifact');if(art.length!==1||new Set(checks.map(r=>r.check_id)).size!==checks.length)fail('invalid_mapping','/requirements','one artifact and unique check IDs required');for(const r of v.requirements)if(r.kind==='check'?(r.check_id===null||r.artifact_path!==null):(r.artifact_path===null||r.check_id!==null))fail('invalid_mapping','/requirements','requirement fields inconsistent');
 for(const a of v.assertions){if(!spanMatches(Buffer.from(v.statement),a.span,a.text))fail('invalid_mapping','/assertions','statement span mismatch');if(a.requirement_ids.some(id=>!v.requirements.some(r=>r.id===id)))fail('invalid_mapping','/assertions','unknown requirement');const expected=a.predicate==='receipt_revision'?[]:a.predicate==='all_checks_ran'?checks.map(r=>r.id):a.predicate==='artifact_created'?art.map(r=>r.id):null;if(expected&&(expected.length!==a.requirement_ids.length||expected.some(id=>!a.requirement_ids.includes(id))||(a.predicate==='all_checks_ran'&&!expected.length)))fail('invalid_mapping','/assertions','predicate requirement mapping mismatch');}
 if(v.narrower_observation&&v.assertions.some(a=>a.id===v.narrower_observation.id))fail('invalid_mapping','/narrower_observation/id','assertion ID collision');
 }if(name==='observations'){unique(v.checks,'/checks');unique(v.writes,'/writes');if((v.artifact.state==='present')!==(v.artifact.sha256!==null))fail('invalid_shape','/artifact/sha256','artifact digest inconsistent');for(const w of v.writes)if((w.outcome==='created')!==(w.sha256!==null))fail('invalid_shape','/writes','event digest inconsistent');if(v.observer.origin==='locally-observed'&&(v.checks.length||v.writes.length))fail('invalid_shape','/observer/origin','collector cannot claim imported execution observations');}
 return v;
}
function caught(e,s,p=''){return issue(e.code&&['malformed_json','duplicate_key','trailing_content','unsupported_version','invalid_shape','invalid_mapping','source_unavailable','source_digest_mismatch','selection_rejected','input_limit','binding_mismatch','execution_lock_missing'].includes(e.code)?e.code:'source_unavailable',s,e.path??p,e.message||'source unavailable');}
export function loadLock(p,digest){try{if(!/^[a-f0-9]{64}$/.test(digest??''))throw Error('reviewed digest required');const bytes=readBytes(p,JSON_LIMIT);if(sha256(bytes)!==digest)throw Error('reviewed digest mismatch');const lock=admit('executionLock',strictJson(bytes));if(canonicalJson(lock.inputs.map(x=>x.path))!==canonicalJson(INPUTS))throw Error('lock must name exactly 43 ordered paths');for(const item of lock.inputs)if(sha256(readBytes(selected(ROOT,item.path)))!==item.sha256)throw Error('lock input mismatch: '+item.path);return {lock,id:digest};}catch(e){fail('execution_lock_missing','/execution_lock',e.message);}}
const rank={complete:0,partial:1,unknown:2};
function merge(...cs){return {completeness:cs.reduce((a,c)=>rank[c.completeness]>rank[a]?c.completeness:a,'complete'),warnings:cs.flatMap(c=>c.warnings)};}
const complete=()=>({completeness:'complete',warnings:[]});
function repositoryCapture(m){const r=m.repository;const warnings=[];let c='complete';if(!r.before||!r.after){c='unknown';warnings.push('repository unavailable');}if(r.before?.dirty||r.after?.dirty){if(c!=='unknown')c='partial';warnings.push('repository dirty');}if(r.before&&r.after&&!same(r.before.revision,r.after.revision)){if(c!=='unknown')c='partial';warnings.push('repository revision changed');}return merge(m.capture.repository,{completeness:c,warnings});}
function artifactCapture(m){let c='complete';const warnings=[];if(m.artifact.state==='unavailable'){c='unknown';warnings.push('artifact unavailable');}if(m.artifact.stable===null){c='unknown';warnings.push('artifact stability unknown');}if(m.artifact.stable===false){if(c!=='unknown')c='partial';warnings.push('artifact unstable');}return merge(m.capture.artifact,{completeness:c,warnings});}
function nativeContext(values,records,lock){const receipt=values.receipt??null,result=values.result??null,invocation=values.observations?.verifier_invocation??null;const errors=records.filter(r=>['receipt','result'].includes(r.descriptor.role)).flatMap(r=>r.errors);const limitations=['Native records do not certify execution, authenticity, correctness or permission.'];if(records.some(r=>r.descriptor.origin.kind==='synthetic'))limitations.unshift('Synthetic provenance; no execution/authenticity certification.');let linkage='unbound',repository_binding='unbound';const bad=(s,p,msg)=>errors.push(issue('binding_mismatch',s,p,msg));const byRole=r=>records.find(s=>s.descriptor.role===r);
 if(invocation&&receipt&&result){const s=byRole('observations').descriptor.id,i=invocation;if(i.receipt_sha256!==byRole('receipt').observed_sha256||i.result_sha256!==byRole('result').observed_sha256)bad(s,'/verifier_invocation','native byte binding mismatch');if(i.operation!==result.operation||((i.exit_status===0)!==result.ok))bad(s,'/verifier_invocation','operation/exit binding mismatch');if(!same(i.tool_commit,lock.evidencegate.commit)||i.tool_version!==lock.evidencegate.version)bad(s,'/verifier_invocation','tool pin mismatch');if(i.operation==='validate'&&(i.repository_before!==null||i.repository_after!==null))bad(s,'/verifier_invocation','validate states must be null');linkage=i.origin==='locally-observed'?'locally-captured':'producer-reported';}
 if(result&&((result.operation==='validate'&&result.repository_checked)||(result.operation==='verify'&&result.ok&&!result.repository_checked)))bad(byRole('result').descriptor.id,'/repository_checked','operation/repository binding mismatch');
 if(errors.length)linkage='invalid';if(!invocation)limitations.push('Verifier invocation absent; linkage unbound.');
 if(result?.repository_checked===false)repository_binding='not-checked';else if(result?.repository_checked){if(linkage==='invalid')repository_binding='invalid';else if(!invocation)repository_binding='unbound';else{const {repository_before:a,repository_after:b}=invocation;repository_binding=a&&b&&!a.dirty&&!b.dirty&&same(a.revision,b.revision)&&same(a.revision,receipt?.subject.head_sha)?'stable':'limited';if(repository_binding==='limited')limitations.push('Recorded verifier repository states are unavailable, dirty, changing or revision-mismatched.');}}
 return {receipt,result,invocation,linkage,repository_binding,limitations,errors};
}
export function evaluatePacketBytes(packetBytes,evidenceRoot,lock,lockId){
 const packet_sha256=sha256(packetBytes);let p;try{p=admit('packet',strictJson(packetBytes));}catch(e){return {schema_version:'daid_handoff_error_v1',packet_sha256,errors:[caught(e,null)],downstream_action_authorized:false};}
 const values={},records=p.sources.map(descriptor=>({descriptor,admission:'not-read',observed_sha256:null,errors:[]}));const get=r=>records.find(s=>s.descriptor.role===r);
 function read(role){const r=get(role),d=r.descriptor;try{const raw=readBytes(selected(evidenceRoot,d.path),['receipt','result','observations'].includes(role)?JSON_LIMIT:FILE_LIMIT);r.observed_sha256=sha256(raw);if(r.observed_sha256!==d.sha256)fail('source_digest_mismatch','','selected bytes differ from descriptor');if(role==='expectations'){let t;try{t=new TextDecoder('utf-8',{fatal:true}).decode(raw);}catch{fail('invalid_shape','','expectations are not UTF-8');}for(const q of p.requirements)if(!spanMatches(raw,q.span,q.text))fail('invalid_mapping','/requirements','expectation span mismatch');values[role]=t;}else if(role!=='artifact')values[role]=admit({receipt:'nativeReceipt',result:'nativeResult',observations:'observations'}[role],strictJson(raw));else values[role]=raw;r.admission='accepted';}catch(e){r.admission='error';r.errors.push(caught(e,d.id));}}
 for(const d of p.sources)if(d.role!=='artifact')read(d.role);
 if(values.observations){const a=values.observations.artifact,r=get('artifact');if((a.state==='present')!==(r.descriptor.sha256!==null)){r.admission='error';r.errors.push(issue('invalid_shape',r.descriptor.id,'/sha256','artifact presence/digest declaration inconsistent'));}else if(a.state==='present'){read('artifact');if(r.admission==='accepted'&&a.sha256!==r.observed_sha256){r.admission='error';r.errors.push(issue('source_digest_mismatch',r.descriptor.id,'/artifact/sha256','manifest artifact digest differs'));delete values.artifact;}}}
 const native_context=nativeContext(values,records,lock),m=values.observations;
 const checks=p.requirements.filter(r=>r.kind==='check'),artifact=p.requirements.find(r=>r.kind==='artifact');
 const applicable=!!m&&m.subject.id===p.subject.id&&same(m.subject.revision,p.subject.revision)&&m.subject.attempt_id===p.subject.attempt_id;
 const rowApplicable=r=>applicable&&same(r.revision,p.subject.revision)&&r.attempt_id===p.subject.attempt_id;
 const assessedRequirements=new Set(p.assertions.filter(a=>a.predicate!=='unassessed').flatMap(a=>a.requirement_ids));
 const coverage={expected_check_ids:values.expectations===undefined?null:checks.map(r=>r.check_id),observed_check_ids:m?m.checks.filter(r=>rowApplicable(r)&&r.outcome.startsWith('executed-')).map(r=>r.id):null,missing_check_ids:null,skipped_check_ids:null,extra_check_ids:null,unmapped_requirement_ids:p.requirements.filter(r=>!assessedRequirements.has(r.id)).map(r=>r.id),unassessed_assertion_ids:p.assertions.filter(a=>a.predicate==='unassessed').map(a=>a.id)};
 if(m&&coverage.expected_check_ids){coverage.missing_check_ids=checks.filter(q=>!m.checks.some(r=>r.id===q.check_id&&rowApplicable(r)&&r.outcome!=='not-observed')).map(q=>q.check_id);coverage.skipped_check_ids=checks.filter(q=>m.checks.some(r=>r.id===q.check_id&&rowApplicable(r)&&r.outcome==='skipped')).map(q=>q.check_id);coverage.extra_check_ids=m.checks.filter(r=>!coverage.expected_check_ids.includes(r.id)).map(r=>r.id);}
 const assessments=[];
 function assessment(a,narrow=false){const pred=narrow?'artifact_presence':a.predicate;const result={id:a.id,status:'unassessed',predicate:pred,acc_input:null,acc_receipt:null,errors:[],missing_evidence:[]};if(pred==='unassessed')return result;
 const deps=pred==='receipt_revision'?['receipt']:pred==='all_checks_ran'?['expectations','observations']:pred==='artifact_created'?['expectations','observations','artifact']:['observations','artifact'];result.errors=records.filter(r=>deps.includes(r.descriptor.role)).flatMap(r=>r.errors);if(result.errors.length){result.status='error';return result;}
 const evidence=[];const item=(id,requirement,state,role,ref,extra={})=>{const r=get(role);evidence.push({id,requirement,state,source_ref:`${r.descriptor.id}:${r.observed_sha256??r.descriptor.sha256??'unavailable'}:${ref}`, ...(r.observed_sha256?{source_sha256:r.observed_sha256}:{}),...extra});if(state!=='supports')result.missing_evidence.push(`${id}: ${state}`);};
 let capture=complete();
 if(pred==='receipt_revision'){item('receipt-revision','Recorded receipt head equals claimed revision',same(values.receipt.subject.head_sha,p.subject.revision)?'supports':'contradictory','receipt','/subject/head_sha',{source_revision:values.receipt.subject.head_sha});}
 else {const repo=repositoryCapture(m),art=artifactCapture(m);capture=pred==='all_checks_ran'?merge(m.capture.shared,repo,m.capture.checks):pred==='artifact_created'?merge(m.capture.shared,repo,art):merge(m.capture.shared,art);
 if(pred==='all_checks_ran'||pred==='artifact_created'){
 item('subject','Manifest subject and attempt match the packet',applicable?'supports':'inapplicable','observations','/subject');
 if(p.expectations_complete!==true)capture=merge(capture,{completeness:p.expectations_complete===false?'partial':'unknown',warnings:[p.expectations_complete===false?'expectation list incomplete':'expectation list completeness unknown']});
 }
 if(pred==='all_checks_ran')for(const q of checks){const i=m.checks.findIndex(r=>r.id===q.check_id),r=m.checks[i];const state=!applicable?'inapplicable':!r?'absent':!same(r.revision,p.subject.revision)?'stale':r.attempt_id!==p.subject.attempt_id?'inapplicable':r.outcome==='not-observed'?'unknown':r.outcome==='skipped'?'contradictory':'supports';item('check-'+q.check_id,q.text,state,'observations',i<0?'/checks':`/checks/${i}`,r?{observed_value:r.outcome,source_revision:r.revision}:{});}
 if(pred==='artifact_created'){
 const stableRepo=m.repository.before&&m.repository.after&&!m.repository.before.dirty&&!m.repository.after.dirty&&same(m.repository.before.revision,p.subject.revision)&&same(m.repository.after.revision,p.subject.revision);item('repository','Clean stable repository at claimed revision',stableRepo?'supports':'unknown','observations','/repository');
 const matching=m.artifact.path===artifact.artifact_path;const snapshot=matching&&m.artifact.state==='present'&&m.artifact.stable===true;item('snapshot','Stable present selected artifact at required path',!matching?'inapplicable':snapshot?'supports':'unknown','observations','/artifact');
 const events=m.writes.map((w,i)=>({w,i})).filter(({w})=>w.path===artifact.artifact_path);if(!events.length)item('event-absent','Creation event for this attempt','absent','observations','/writes');
 for(const {w,i} of events){const state=!applicable?'inapplicable':!same(w.revision,p.subject.revision)?'stale':w.attempt_id!==p.subject.attempt_id?'inapplicable':w.outcome==='not-created'?'contradictory':w.outcome==='created'&&snapshot&&stableRepo&&w.sha256===get('artifact').observed_sha256?'supports':'unknown';item('event-'+w.id,'Creation event bound to this attempt and selected bytes',state,'observations',`/writes/${i}`,{observed_value:w.outcome,source_revision:w.revision});}
 }
 if(pred==='artifact_presence'){const ar=m.artifact;const state=ar.path!==a.artifact_path?'inapplicable':ar.stable!==true||ar.state==='unavailable'?'unknown':ar.state==='absent'?'contradictory':get('artifact').observed_sha256===a.sha256?'supports':'contradictory';item('artifact-presence','Present bytes at this snapshot match narrower digest',state,'observations','/artifact');}
 }
 if(p.capture_gaps.length)capture=merge(capture,{completeness:'partial',warnings:p.capture_gaps});const acc_input={schema_version:'daid_agent_claim_check_input_v1',claim:{id:a.id,text:a.text,type:pred==='artifact_created'?'artifact-created':'other'},evidence,capture:{completeness:capture.completeness,adapter_warnings:capture.warnings}};const acc=evaluateAgentClaimBytes(Buffer.from(canonicalJson(acc_input)));if(!acc.accepted)throw Error('ACC compatibility failure: '+acc.output);return {...result,status:'assessed',acc_input,acc_receipt:acc.value};
 }
 for(const a of p.assertions)assessments.push(assessment(a));if(p.narrower_observation)assessments.push(assessment(p.narrower_observation,true));
 const errors=[...records.flatMap(r=>r.errors),...native_context.errors.filter(e=>!records.some(r=>r.errors.includes(e)))];
 const incomplete=!!(errors.length||coverage.unmapped_requirement_ids.length||coverage.unassessed_assertion_ids.length||p.capture_gaps.length||p.expectations_complete!==true||native_context.linkage==='unbound'||native_context.linkage==='invalid'||native_context.repository_binding==='limited'||assessments.some(a=>a.status!=='assessed'||a.acc_receipt.finding==='insufficient_evidence'||a.acc_input.capture.completeness!=='complete'||a.acc_input.capture.adapter_warnings.length));
 const {schema_version,sources,...preserved}=p;return {schema_version:'daid_handoff_report_v1',packet_sha256,execution_lock_id:lockId,...preserved,sources:records,native_context,assessments,coverage,errors,incomplete,intent_assessment:'not-assessed',downstream_action_authorized:false};
}
export function markdown(value){const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');return '# DAID handoff report\n\nIntent: not assessed. Downstream action authorized: false.\n\n<pre>'+escape(JSON.stringify(JSON.parse(canonicalJson(value)),null,2))+'</pre>\n';}
export function checkPacket(packetPath,lockPath,digest){let admitted;try{admitted=loadLock(lockPath,digest);}catch(e){return {schema_version:'daid_handoff_error_v1',packet_sha256:null,errors:[caught(e,null,'/execution_lock')],downstream_action_authorized:false};}let bytes;try{bytes=readBytes(checkedPath(path.resolve(packetPath)),JSON_LIMIT);return evaluatePacketBytes(bytes,path.dirname(path.resolve(packetPath)),admitted.lock,admitted.id);}catch(e){return {schema_version:'daid_handoff_error_v1',packet_sha256:bytes?sha256(bytes):null,errors:[caught(e,null)],downstream_action_authorized:false};}}
function gitState(root){const env={...process.env,GIT_OPTIONAL_LOCKS:'0'};const a=spawnSync('git',['-C',root,'rev-parse','HEAD'],{env,encoding:'utf8',timeout:30000});const b=spawnSync('git',['-C',root,'status','--porcelain=v1','--untracked-files=all'],{env,encoding:'utf8',timeout:30000});return a.status===0&&b.status===0&&/^[a-f0-9]{40}$/.test(a.stdout.trim())?{revision:a.stdout.trim(),dirty:!!b.stdout}:null;}
function fileState(root,rel){try{return {state:'present',sha256:sha256(readBytes(selected(root,rel))) };}catch(e){if(e.code==='ENOENT')return {state:'absent',sha256:null};if(e.code==='selection_rejected'||e.code==='input_limit')throw e;return {state:'unavailable',sha256:null};}}
export function collectSelectionBytes(bytes){const s=admit('selection',strictJson(bytes));checkedPath(s.repository_root,{directory:true});checkedPath(s.evidence_root,{directory:true});checkedPath(s.output_path,{missing:true});if(s.output_path===s.repository_root||s.output_path.startsWith(s.repository_root+'/'))fail('selection_rejected','/output_path','output must be outside repository');if(fs.existsSync(s.output_path))fail('selection_rejected','/output_path','output exists');const before=gitState(s.repository_root),a=fileState(s.repository_root,s.artifact_path),b=fileState(s.repository_root,s.artifact_path),after=gitState(s.repository_root);const artifact={path:s.artifact_path,state:b.state,sha256:b.sha256,before_sha256:a.sha256,stable:a.state==='unavailable'||b.state==='unavailable'?null:a.state===b.state&&a.sha256===b.sha256};const m={schema_version:'daid_handoff_observations_v1',observer:{id:s.observer_id,version:VERSION,origin:'locally-observed'},subject:s.subject,captured_at:new Date().toISOString(),capture:{shared:complete(),repository:complete(),checks:{completeness:'unknown',warnings:['execution not observed']},artifact:complete()},repository:{before,after},checks:[],artifact,writes:[],verifier_invocation:null};m.capture.repository=repositoryCapture(m);m.capture.artifact=artifactCapture(m);admit('observations',m);fs.writeFileSync(s.output_path,canonicalJson(m),{flag:'wx',mode:0o600});return m;}
